[[constraint]]
  branch = "master"
  name = "github.com/kurrik/oauth1a"

[[constraint]]
  branch = "master"
  name = "github.com/kurrik/twittergo"

[[constraint]]
  name = "github.com/manifoldco/promptui"
  version = "0.3.1"

[prune]
  go-tests = true
  unused-packages = true
